DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  order_no VARCHAR(16) NOT NULL,
  sub_total INTEGER NOT NULL DEFAULT 0,
  taxes INTEGER NOT NULL DEFAULT 0,
  total INTEGER NOT NULL DEFAULT 0,
  placed_at TIMESTAMP,
  order_status INTEGER NOT NULL DEFAULT 0,
  waiting_time INTEGER DEFAULT NULL
);
