DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  total_items INTEGER NOT NULL,
  taxes INTEGER NOT NULL,
  total_cost INTEGER NOT NULL
);
