DROP TABLE IF EXISTS donuts CASCADE;
CREATE TABLE donuts (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  thumbnail_photo_url VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  available BOOLEAN DEFAULT TRUE,
  added_at DATE NOT NULl
);
