DROP TABLE IF EXISTS donuts CASCADE;
CREATE TABLE donuts (
  id SERIAL PRIMARY KEY NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  price INTEGER NOT NULL,
  description TEXT NOT NULL
);
